DEBUG = True
# SQLALCHEMY_ECHO = True  # 打印sql语句
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:341125@localhost:3306/order'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ENCODING = "utf-8"
# RELEASE_VERSION = "20181121001"
